# Generated by Django 3.1.4 on 2022-06-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish_reports', '0003_auto_20220615_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentstats',
            name='existing_worklist',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Exisiting On Worklist'),
        ),
        migrations.AddField(
            model_name='recruitmentstats',
            name='expected_worklist',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected On Worklist'),
        ),
    ]
