# Generated by Django 3.1.4 on 2022-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish_reports', '0004_auto_20220615_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentstats',
            name='not_randomised',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Not randomised & not attempted'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='continued_contact',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Continued contact'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='dataset_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dataset totals'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='existing_locator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Existing locator'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='existing_worklist',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Exisiting on worklist'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='expected_locator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected locator'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='expected_worklist',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected on worklist'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='missing_locator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Missing locator'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='missing_worklist',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Missing on worklist'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='not_reacheble',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Not reacheble'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='not_total_attempted',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total not attempted'),
        ),
        migrations.AlterField(
            model_name='recruitmentstats',
            name='total_attempts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total attempts'),
        ),
    ]
