# Generated by Django 3.1.4 on 2022-06-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flourish_reports', '0006_auto_20220615_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentstats',
            name='continued_contact',
        ),
    ]
