# Generated by Django 3.1.4 on 2022-06-15 17:50

import _socket
from django.db import migrations, models
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('flourish_reports', '0008_auto_20220615_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieTotalStats',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('mpepu', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Mpepu')),
                ('tshipidi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tshipidi')),
                ('mashi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mashi')),
                ('mma_bana', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mma bana study')),
                ('tshilo_dikotla', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tshilo dikotla study')),
                ('total_continued_contact', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total continued contact')),
                ('total_decline_uninterested', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total decline uninterested')),
                ('total_consented', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total consented')),
                ('total_unable_to_reach', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total unable to reach')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
